export { default as Main } from './Main/Main'
export { default as BlogPage } from './Blog/BlogPage'
export { default as ProjectPage } from './Project/ProjectPage'
export { default as Copier } from './Copier/Copier'
export { default as Galaxy } from './Galaxy/Galaxy'